---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: add neovim repo
      become: yes
      become_method: sudo
      command: add-apt-repository -y ppa:neovim-ppa/unstable

    - name: update
      become: yes
      become_method: sudo
      apt:
        update_cache: yes
      tags:
        - common

    - name: install all prerequisites
      become: yes
      become_method: sudo
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - libevent-dev
        - libncurses-dev
        - libpq-dev
        - libreadline-dev
        - libssl-dev
        - git
        - python-dev
        - python-pip
        - python3-dev
        - python3-pip
        - python3-setuptools
        - sakura
        - silversearcher-ag
        - software-properties-common
        - xclip
        - zlib1g-dev
      tags:
        - common

    - name: install neovim
      become: yes
      become_method: sudo
      apt: name=neovim state=present

    - name: install neovim python
      become: yes
      become_method: sudo
      pip: name=neovim executable=pip3 state=present

    - name: install vim-plug
      command: curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: install nodenv
      git: repo=https://github.com/nodenv/nodenv.git dest=~/.nodenv
    
    - name: build nodenv bash extension
      shell: cd ~/.nodenv && src/configure && make -C src
      
    - name: add nodenv to path
      lineinfile:
        dest: ~/.bashrc
        line: >
          export PATH="$HOME/.nodenv/bin:$PATH"
      
    - name: add nodenv init to bashrc
      lineinfile:
        dest: ~/.bashrc
        line: >
          eval "$(nodenv init -)"
      
    - name: install node-build
      git: repo=https://github.com/nodenv/node-build.git dest=~/.nodenv/plugins/node-build
      
    - name: install node 6.9.1
      shell: ~/.nodenv/bin/nodenv install 6.9.1
      
    - name: set global node
      shell: ~/.nodenv/bin/nodenv global 6.9.1

    - name: install rbenv
      git: repo=https://github.com/rbenv/rbenv.git dest=~/.rbenv
      tags:
        - ruby

    - name: compile rbenv bash extension
      shell: cd ~/.rbenv && src/configure && make -C src
      tags:
        - ruby

    - name: add rbenv to path
      lineinfile:
        dest: ~/.bashrc
        line: >
          export PATH="$HOME/.rbenv/bin:$PATH"
      tags:
        - ruby

    - name: add rbenv init to bashrc
      lineinfile:
        dest: ~/.bashrc
        line: >
          eval "$(rbenv init -)"
      tags:
        - ruby

    - name: install ruby-build
      git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build
      tags:
        - ruby

    - name: install ruby 2.3.3
      shell: ~/.rbenv/bin/rbenv install 2.3.3
      tags:
        - ruby

    - name: set global ruby
      shell: ~/.rbenv/bin/rbenv global 2.3.3
      tags:
        - ruby


    - name: build tmux (with tc support)
      become: yes
      become_method: sudo
      shell: cd ~ && \
        wget https://github.com/tmux/tmux/releases/download/2.2/tmux-2.2.tar.gz && \
        tar -xzvf tmux-2.2.tar.gz && \
        cd tmux-2.2 && \
        ./configure && \
        make && \
        make install

    - name: check out dotfiles
      git: repo=https://github.com/tyrbo/dotfiles.git dest=~/.config/dotfiles

    - name: install dotfiles
      shell: cd ~/.config/dotfiles && ./install

    - name: install nvim plugins
      shell: nvim --headless +PlugInstall +qall
